include: package:very_good_analysis/analysis_options.yaml

analyzer:
    exclude:
        [
            lib/**.g.dart,
            lib/**.gen.dart,
            test/.test_coverage.dart,
            bin/cache/**,
            lib/generated_plugin_registrant.dart,
        ]

linter:
    rules:
        sort_pub_dependencies: false
        flutter_style_todos: false
        public_member_api_docs: false
        always_use_package_imports: false
